# Generated by Django 5.2.8 on 2025-11-22 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='about',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
